# Generated by Django 6.0.4 on 2026-04-23 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharedfile',
            name='password',
        ),
    ]
